# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c474631ec2883ce1de3d65668c8adbb67c52d53073e3b0d9452d976f0742a756c0dab4e5b2b8f31de73bfdaa52e3cc61f1c66e900bae1940aac8c76436470130

test:
  secret_key_base: e6da4d72dba1dd20693d6e38c590df07627af7ac6a1160015a9f2076165467caf538239e88863d97c444bc4276a2b6a1afd23ba5629e8a776be20a01254c77e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
